apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp
  target:
    name: postgresql
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: a-team-postgresql
