apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gcp
  target:
    name: db
    creationPolicy: Owner
  data:
  - secretKey: credentials
    remoteRef:
      key: my-secret
