apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp
spec:
  provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcp-secret
              key: credentials
        projectID: dot-20220515145748
